name: Build and Upload Artifact

on:
  push:
    branches:
      - main
      - main-temp
  pull_request:
    branches:
      - "main"
      - "main-temp"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install acpica-tools
          cd src
          pip3 install ./

      - name: Generate Artifact
        run: |
          cd src/test/kernel
          igvmgen -o kernelinitrd.bin -kernel bzImage -append "8250_core.nr_uarts=0 panic=-1 debug loglevel=7 root=/dev/sda rdinit=/startup.sh" -rdinit initramfs.cpio.gz -vtl 0
          ${{ github.workspace }}/src/test/kernel/vmgstool create --filepath kernelinitrd.vmgs --filesize 67108864
          ${{ github.workspace }}/src/test/kernel/vmgstool write --filepath kernelinitrd.vmgs --datapath kernelinitrd.bin -i=8

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: src/test/kernel/kernelinitrd.vmgs
