name: Run tests

on:
  push:
    branches:
      - "main"
      - "main-temp"
  pull_request:
    branches:
      - "main"
      - "main-temp"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
         python-version: [3.8, 3.9]

    steps:
          - name: Checkout repo
            uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
          - name: Set Up Python ${{ matrix.python-version }}
            uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
            with:
              python-version: ${{ matrix.python-version }}
          - name: Install deps
            run: |
              sudo apt update
              sudo apt install acpica-tools

          - name: Run pytest
            run: |
              pushd src
              pip install ./
              popd
              pytest test
